[workspace]
channels = ["conda-forge"]
name = "stats-tools"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cabinetry = ">=0.6.0,<0.7"
hist = ">=2.8.1,<3"
dask = ">=2025.4.0,<2025.5.0"
distributed = ">=2025.4.0,<2025.5.0"
